# ~/.config/zabrze/config.yaml
abbrevs:
  # global settings
  - name: null command
    abbr: "null"
    snippet: "> /dev/null 2>&1"
    global: true

  # git
  - name: git
    abbr: g
    snippet: git

  - name: git push safe
    abbr: gps
    snippet: git push --force-with-lease --force-if-includes


  - name: git current branch
    abbr: b
    snippet: $(git symbolic-ref --short HEAD)
    evaluate: true
    global: true
    context: '^git\s'
  
  - name: remote branch
    abbr: o
    snippet: origin
    global: true
    context: '^git\s'

  # github cli (gh)
  - name: gh auth switch
    abbr: ghs
    snippet: gh auth switch

  - name: gh auth setup-git
    abbr: ghags
    snippet: gh auth setup-git

  - name: gh pr create
    abbr: ghprc
    snippet: gh pr create

  - name: cargo installed app update
    abbr: cup
    snippet: cargo install-update -a

  # eza
  - name: ls with icons and git
    abbr: ls
    snippet: eza --icons --git
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: lt
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv"
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: ltl
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv" -l --icons
    if: (( ${+commands[eza]} ))

  # chezmoi
  - name: chezmoi
    abbr: cz
    snippet: chezmoi
    if: (( ${+commands[chezmoi]} ))

  # pnpm
  - name: pnpm dlx
    abbr: plx
    snippet: pnpm dlx

  # docker
  - name: docker run it
    abbr: dcr
    snippet: docker run -it

  - name: docker compose
    abbr: dc
    snippet: docker compose

  - name: docker compose up
    abbr: dcu
    snippet: docker compose up


  - name: docker compose down
    abbr: dcd
    snippet: docker compose down

  - name: docker compose logs
    abbr: dcl
    snippet: docker compose logs

  # terraform
  - name: terraform
    abbr: tf
    snippet: terraform

  - name: terraform init
    abbr: tfi
    snippet: terraform init

  - name: terraform plan
    abbr: tfp
    snippet: terraform plan

  - name: terraform apply
    abbr: tfa
    snippet: terraform apply

  # venv (python)
  - name: venv activate
    abbr: va
    snippet: source .venv/bin/activate

  - name: venv deactivate
    abbr: vd
    snippet: deactivate
