# ~/.config/zabrze/config.yaml
abbrevs:
  # git
  - name: git
    abbr: g
    snippet: git
  
  # github cli (gh)
  - name: gh auth switch
    abbr: ghs
    snippet: gh auth switch
  
  - name: gh auth setup-git
    abbr: ghags
    snippet: gh auth setup-git

  - name: gh pr create
    abbr: ghprc
    snippet: gh pr create

  - name: cargo installed app update
    abbr: "cup"
    snippet: cargo install-update -a

  # eza
  - name: ls with icons and git
    abbr: ls
    snippet: eza --icons --git
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: lt
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv"
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: ltl
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv" -l --icons
    if: (( ${+commands[eza]} ))

  # chezmoi
  - name: chezmoi
    abbr: cz
    snippet: chezmoi
    if: (( ${+commands[chezmoi]} ))

  # pnpm
  - name: pnpm dlx
    abbr: plx
    snippet: pnpm dlx
