# ~/.config/zabrze/config.yaml
abbrevs:
  # global settings
  - name: null command
    abbr: "null"
    snippet: "> /dev/null 2>&1"
    global: true

  # git
  - name: git
    abbr: g
    snippet: git

  - name: git safe push
    abbr: gsp
    snippet: git push --force-with-lease --force-if-includes

  - name: git current branch
    abbr: b
    snippet: $(git symbolic-ref --short HEAD)
    evaluate: true
    global: true
    context: '^git\s'

  - name: remote branch
    abbr: o
    snippet: origin
    global: true
    context: '^git\s'

  - name: git pull
    abbr: gpl
    snippet: git pull
  
  - name: git pull(alias)
    abbr: p
    snippet: pull
    global: true
    context: '^git\s'
  
  - name: swich main branch
    abbr: gsm
    snippet: git switch main
  
  - name: swich main branch(alias)
    abbr: sm
    snippet: switch main
    global: true
    context: '^git\s'

  # github cli (gh)
  - name: gh auth switch
    abbr: ghs
    snippet: gh auth switch

  - name: gh auth setup-git
    abbr: ghags
    snippet: gh auth setup-git

  - name: gh pr create
    abbr: ghprc
    snippet: gh pr create

  - name: gh pr view and checkout fuzzy
    abbr: gfs
    snippet: github-fuzzy-switch

  - name: cargo installed app update
    abbr: cup
    snippet: cargo install-update -a

  # eza
  - name: ls with icons and git
    abbr: ls
    snippet: eza --icons --git
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: lt
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv"
    if: (( ${+commands[eza]} ))

  - name: lt with icons and git and ignore node_modules|.git|.cache|.venv
    abbr: ltl
    snippet: eza -T -L 3 -a -I "node_modules|.git|.cache|.venv" -l --icons
    if: (( ${+commands[eza]} ))

  # chezmoi
  - name: chezmoi
    abbr: cz
    snippet: chezmoi
    if: (( ${+commands[chezmoi]} ))

  - name: chezmoi update
    abbr: czu
    snippet: chezmoi update
    if: (( ${+commands[chezmoi]} ))

  # pnpm
  - name: pnpm dlx
    abbr: plx
    snippet: pnpm dlx

  # docker
  - name: docker run it
    abbr: dcr
    snippet: docker run -it

  - name: docker compose
    abbr: dc
    snippet: docker compose

  - name: docker compose up
    abbr: dcu
    snippet: docker compose up

  - name: docker compose down
    abbr: dcd
    snippet: docker compose down

  - name: docker compose logs
    abbr: dcl
    snippet: docker compose logs

  # terraform
  - name: terraform
    abbr: tf
    snippet: terraform

  - name: terraform init
    abbr: tfi
    snippet: terraform init

  - name: terraform plan
    abbr: tfp
    snippet: terraform plan

  - name: terraform apply
    abbr: tfa
    snippet: terraform apply

  # venv (python)
  - name: venv activate
    abbr: va
    snippet: source .venv/bin/activate

  - name: venv deactivate
    abbr: vd
    snippet: deactivate

  # vscode
  - name: code
    abbr: c
    snippet: code .
    if: (( ! ${+commands[cursor]} ))
  
  # Cursor
  - name: cursor
    abbr: c
    snippet: cursor .
    if: (( ${+commands[cursor]} ))

  # mise
  - name: mise
    abbr: m
    snippet: mise

  - name: mise run
    abbr: mr
    snippet: mise run
  
  - name: gal
    abbr: g
    snippet: gal
    evaluate: true
    global: true
    # mise run
    context: '^mise\s'
