# starshipの設定
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

## 基本
add_newline = true

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"
style = "#392467 bold"

[container]
disabled = true

[docker_context]
format = "via [󰡨 $context](blue bold)"

[gcloud]
disabled = true

[username]
style_user = "#A8D8EA bold"
format = "[ $user]($style) in "
disabled = true
show_always = true

[git_branch]
style = "#5D3587"
symbol = " "

[git_status]
style = "#5D3587"

[package]
style = "#A367B1"
symbol = " "

[nodejs]
style = "#FFD1E3"

[python]
style = "#FFD1E3"
symbol = " "