name: Check

on:
  pull_request:
    branches:
      - main
    paths:
      - ./scripts/**

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test setup
        run: sh -c "$(curl -fsSL get.chezmoi.io)" -- init --apply -S .

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: test setup
        run: |
          sh -c "$(curl -fsSL get.chezmoi.io)" -- init --apply -S .
